// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduleEntry = { id: string, threadId: string, prompt: string, intervalSeconds: bigint, nextRunAt: bigint, createdAt: bigint, updatedAt: bigint, lastRunStartedAt: bigint | null, lastRunCompletedAt: bigint | null, lastError: string | null, runCount: bigint, status: string, };
